### ISSUE TITLE
【依頼】アイコン変えてくれたら嬉しいです @ahaha0807

### ISSUE THREAD

**Issue by ahaha0807** [ITCreate/itc-official-site#10]
## 概要
アイコンを切り替えたため、リンク先のアイコンに変えていただけると嬉しいです…

## リンク先
https://avatars.githubusercontent.com/ahaha0807

**Comment by mogumannto** [comment]
変更done

**Comment by ahaha0807** [comment]
@mogumannto ありがとう！closeします！
